import { Theme } from '@radix-ui/themes'
import type { Metadata } from 'next'
import '@radix-ui/themes/styles.css'
import '@/shared/styles/globals.css'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'
import { notFound } from 'next/navigation'
import React from 'react'
import { routing } from '../../i18n/routing'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: { lang: string }
}) {
  const { lang } = await params

  // Ensure that the incoming locale is valid
  if (!routing.locales.includes(lang as never)) notFound()

  const translations = await getMessages()

  return (
    <html lang={lang}>
      <body>
        <Theme
          accentColor="jade"
          radius="large"
          grayColor="slate"
          scaling="110%"
        >
          <NextIntlClientProvider messages={translations}>
            {children}
          </NextIntlClientProvider>
        </Theme>
      </body>
    </html>
  )
}
