import { Theme } from '@radix-ui/themes'
import type { Metadata } from 'next'
import '@radix-ui/themes/styles.css'
import '../../_styles/globals.css'
import { NavBar } from '@ui/components/shared/organisms/NavBar/NavBar'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'
import { notFound } from 'next/navigation'
import React from 'react'
import { routing } from '../../_i18n/routing'
import Footer from '@ui/components/shared/organisms/Footer/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: Promise<{ lang: string }>
}) {
  // Ensure that the incoming locale is valid
  const { lang } = await params
  if (!routing.locales.includes(lang as never)) notFound()

  // Providing all translations to the client
  const translations = await getMessages()

  return (
    <html lang={lang}>
      <body>
        <Theme>
          <NextIntlClientProvider messages={translations}>
            <NavBar />

            {children}

            <Footer />
          </NextIntlClientProvider>
        </Theme>
      </body>
    </html>
  )
}
